// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package messaging;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringMessage = 1;</code>
   */
  java.lang.String getStringMessage();
  /**
   * <code>string stringMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringMessageBytes();
}
