// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package messaging;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringRequest = 1;</code>
   */
  java.lang.String getStringRequest();
  /**
   * <code>string stringRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringRequestBytes();
}
