// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package wearables;

public interface HeartRateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearables.HeartRate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rate = 1;</code>
   */
  int getRate();
}
