// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.wearables;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearables.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string replyString = 1;</code>
   */
  java.lang.String getReplyString();
  /**
   * <code>string replyString = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplyStringBytes();
}
