// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.wearables;

public final class service1Impl {
  private service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearables_HeartRate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearables_HeartRate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearables_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearables_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\twearables\"\031\n\tHeartRate" +
      "\022\014\n\004rate\030\001 \001(\005\"\034\n\005Reply\022\023\n\013replyString\030\001" +
      " \001(\t2\205\001\n\020HeartRateService\0224\n\006report\022\024.we" +
      "arables.HeartRate\032\020.wearables.Reply\"\000(\001\022" +
      ";\n\017emergencyReport\022\024.wearables.HeartRate" +
      "\032\020.wearables.Reply\"\000B\033\n\twearablesB\014servi" +
      "ce1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearables_HeartRate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearables_HeartRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearables_HeartRate_descriptor,
        new java.lang.String[] { "Rate", });
    internal_static_wearables_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearables_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearables_Reply_descriptor,
        new java.lang.String[] { "ReplyString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
